{pkgs}:
with pkgs; [
  nodePackages_latest.bash-language-server
  nodePackages_latest.typescript-language-server
  nodePackages_latest.vscode-langservers-extracted
  nodePackages_latest.prettier
  nixd
  python3
  python311Packages.python-lsp-server
  tree
  yaml-language-server
  shellcheck
  taplo
  killport
  fzf
  nixpkgs-fmt
  marksman
  jankyborders
  gopls
  udev-gothic-nf
  fblog
  kotlin-language-server
  hyperfine
  difftastic
  golangci-lint
  stylua
  lua-language-server
  alejandra
]
