# Start AeroSpace at login
start-at-login = true

# Normalizations. See: https://nikitabobko.github.io/AeroSpace/guide#normalization
enable-normalization-opposite-orientation-for-nested-containers = false
enable-normalization-flatten-containers = false

default-root-container-orientation = 'auto'
default-root-container-layout      = 'accordion'

# indent-for-nested-containers-with-the-same-orientation = 30

key-mapping.preset = 'qwerty'

accordion-padding = 30

[gaps]
inner.horizontal = 15
inner.vertical   = 15
outer.left       = 15
outer.bottom     = 15
outer.top        = 15
outer.right      = 15

[mode.main.binding]

ctrl-alt-j = 'exec-and-forget open -na Alacritty'
ctrl-alt-k = 'exec-and-forget open -na Firefox'

alt-slash = 'layout tiles horizontal vertical'
alt-comma = 'layout accordion horizontal vertical'

alt-h = 'focus left'
alt-j = 'focus down'
alt-k = 'focus up'
alt-l = 'focus right'

alt-1 = 'workspace 1'
alt-2 = 'workspace 2'
alt-3 = 'workspace 3'
alt-4 = 'workspace 4'
alt-5 = 'workspace 5'
alt-6 = 'workspace 6'

alt-shift-h = ['join-with left']
alt-shift-j = ['join-with down']
alt-shift-k = ['join-with up']
alt-shift-l = ['join-with right']

ctrl-cmd-h = 'move left'
ctrl-cmd-j = 'move down'
ctrl-cmd-k = 'move up'
ctrl-cmd-l = 'move right'

alt-q = ['move-node-to-workspace 1', 'workspace 1']
alt-w = ['move-node-to-workspace 2', 'workspace 2']
alt-e = ['move-node-to-workspace 3', 'workspace 3']
alt-r = ['move-node-to-workspace 4', 'workspace 4']
alt-t = ['move-node-to-workspace 5', 'workspace 5']
alt-y = ['move-node-to-workspace 6', 'workspace 6']

alt-shift-tab = 'move-workspace-to-monitor --wrap-around next'
alt-tab       = 'workspace-back-and-forth'
cmd-tab       = 'move-node-to-monitor --wrap-around next'

alt-shift-minus = 'resize smart -200'
alt-shift-equal = 'resize smart +200'

[[on-window-detected]]
if.window-title-regex-substring = 'picture-in-picture'
run = ['layout floating']

# alt-shift-semicolon = 'mode service'

# cmd-ctrl-alt-shift-a = 'mode move'

# [mode.service.binding]
# r         = ['flatten-workspace-tree', 'mode main'] # reset layout
# s         = [ 'split opposite', 'mode main'] # sticky is not yet supported https://github.com/nikitabobko/AeroSpace/issues/2
# f         = [ 'layout floating tiling', 'mode main'] # Toggle between floating and tiling layout
# backspace = ['close-all-windows-but-current', 'mode main']
# esc       = ['mode main']

# [mode.move.binding]
# h = 'focus left'
# j = 'focus down'
# k = 'focus up'
# l = 'focus right'
# n = 'focus-monitor next --wrap-around'
# z = 'fullscreen'
# a = 'workspace 1'
# s = 'workspace 2'
# d = 'workspace 3'
# f = 'workspace 4'
# t = 'move-node-to-monitor next --wrap-around'
# tab = 'move-workspace-to-monitor --wrap-around next'
# esc = ['mode main']
# TODO:
# Fix workspaces to windows, throw windows to workspaces

# TODO: Command to throw a workspace to a monitor
# https://nikitabobko.github.io/AeroSpace/commands#move-workspace-to-monitor

# TODO: run slack, alacritty & notion calendar, put in their places
# after-login-command = []

# after-startup-command = []

# All possible keys:
# - Letters.        a, b, c, ..., z
# - Numbers.        0, 1, 2, ..., 9
# - Keypad numbers. keypad0, keypad1, keypad2, ..., keypad9
# - F-keys.         f1, f2, ..., f20
# - Special keys.   minus, equal, period, comma, slash, backslash, quote, semicolon, backtick,
#                   leftSquareBracket, rightSquareBracket, space, enter, esc, backspace, tab
# - Keypad special. keypadClear, keypadDecimalMark, keypadDivide, keypadEnter, keypadEqual,
#                   keypadMinus, keypadMultiply, keypadPlus
# - Arrows.         left, down, up, right

# All possible modifiers: cmd, alt, ctrl, shift

