# Start AeroSpace at login
start-at-login = true

# Normalizations. See: https://nikitabobko.github.io/AeroSpace/guide#normalization
enable-normalization-opposite-orientation-for-nested-containers = true
enable-normalization-flatten-containers = false

default-root-container-orientation = 'auto'
default-root-container-layout      = 'tiles'

indent-for-nested-containers-with-the-same-orientation = 30

key-mapping.preset = 'qwerty'

accordion-padding = 30

[gaps]
inner.horizontal = 15
inner.vertical   = 15
outer.left       = 15
outer.bottom     = 15
outer.top        = 15
outer.right      = 15

[mode.main.binding]

ctrl-alt-j = 'exec-and-forget open -na Alacritty'
ctrl-alt-k = 'exec-and-forget open -na Firefox'

alt-slash = 'layout tiles horizontal vertical'
alt-comma = 'layout accordion horizontal vertical'

alt-h = 'focus left'
alt-j = 'focus down'
alt-k = 'focus up'
alt-l = 'focus right'

alt-a = 'workspace 1'
alt-s = 'workspace 2'
alt-d = 'workspace 3'
alt-f = 'workspace 4'

alt-shift-h = ['join-with left']
alt-shift-j = ['join-with down']
alt-shift-k = ['join-with up']
alt-shift-l = ['join-with right']

alt-shift-a = ['move-node-to-workspace 1', 'workspace 1']
alt-shift-s = ['move-node-to-workspace 2', 'workspace 2']
alt-shift-d = ['move-node-to-workspace 3', 'workspace 3']
alt-shift-f = ['move-node-to-workspace 4', 'workspace 4']

alt-tab       = 'workspace-back-and-forth'
alt-shift-tab = 'move-workspace-to-monitor --wrap-around next'

alt-shift-minus = 'resize smart -50'
alt-shift-equal = 'resize smart +50'

alt-shift-semicolon = 'mode service'

[mode.service.binding]
r         = ['flatten-workspace-tree', 'mode main'] # reset layout
s         = [ 'split opposite', 'mode main'] # sticky is not yet supported https://github.com/nikitabobko/AeroSpace/issues/2
f         = [ 'layout floating tiling', 'mode main'] # Toggle between floating and tiling layout
backspace = ['close-all-windows-but-current', 'mode main']
esc       = ['mode main']

# TODO:
# Fix workspaces to windows, throw windows to workspaces

# TODO: Command to throw a workspace to a monitor
# https://nikitabobko.github.io/AeroSpace/commands#move-workspace-to-monitor

# TODO: run slack, alacritty & notion calendar, put in their places
# after-login-command = []

# after-startup-command = []

# All possible keys:
# - Letters.        a, b, c, ..., z
# - Numbers.        0, 1, 2, ..., 9
# - Keypad numbers. keypad0, keypad1, keypad2, ..., keypad9
# - F-keys.         f1, f2, ..., f20
# - Special keys.   minus, equal, period, comma, slash, backslash, quote, semicolon, backtick,
#                   leftSquareBracket, rightSquareBracket, space, enter, esc, backspace, tab
# - Keypad special. keypadClear, keypadDecimalMark, keypadDivide, keypadEnter, keypadEqual,
#                   keypadMinus, keypadMultiply, keypadPlus
# - Arrows.         left, down, up, right

# All possible modifiers: cmd, alt, ctrl, shift

