"$schema" = "https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json"
version = 2
final_space = true
console_title_template = "{{ .Folder }}"

[[blocks]]
type = "prompt"
alignment = "left"

  [[blocks.segments]]
  type = "path"
  style = "powerline"
  foreground = "lightWhite"
  background = "blue"

[blocks.segments.properties.mapped_locations]
"~/dev" = " "

  [[blocks.segments]]
  type = "go"
  style = "powerline"
  foreground = "black"
  background = "cyan"
  template = "  {{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }} "

    [blocks.segments.properties]
    fetch_version = true

  [[blocks.segments]]
  type = "julia"
  style = "powerline"
  foreground = "black"
  background = "blue"
  template = "  {{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }} "

    [blocks.segments.properties]
    fetch_version = true

  [[blocks.segments]]
  type = "python"
  style = "powerline"
  foreground = "black"
  background = "yellow"
  template = "  {{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }} "

    [blocks.segments.properties]
    display_mode = "files"
    fetch_virtual_env = false

  [[blocks.segments]]
  type = "ruby"
  style = "powerline"
  foreground = "white"
  background = "red"
  template = "  {{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }} "

    [blocks.segments.properties]
    display_mode = "files"
    fetch_version = true

  [[blocks.segments]]
  type = "azfunc"
  style = "powerline"
  foreground = "white"
  background = "magenta"
  template = " {{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }} "

    [blocks.segments.properties]
    display_mode = "files"
    fetch_version = false

  [[blocks.segments]]
  type = "aws"
  style = "powerline"
  foreground = "white"
  background_templates = [
  "{{if contains \"default\" .Profile}}lightRed{{end}}",
  "{{if contains \"jan\" .Profile}}red{{end}}"
]
  template = "  {{ .Profile }}{{ if .Region }}@{{ .Region }}{{ end }} "

    [blocks.segments.properties]
    display_default = false

  [[blocks.segments]]
  type = "root"
  style = "powerline"
  foreground = "black"
  background = "yellow"
  template = "  "

[[blocks]]
type = "prompt"
alignment = "right"

  [[blocks.segments]]
  type = "git"
  style = "powerline"
  foreground = "black"
  background = "lightGreen"
  background_templates = [
  "{{ if or (.Working.Changed) (.Staging.Changed) }}lightMagenta{{ end }}",
  "{{ if and (gt .Ahead 0) (gt .Behind 0) }}red{{ end }}",
  "{{ if gt .Ahead 0 }}lightGreen{{ end }}",
  "{{ if gt .Behind 0 }}green{{ end }}"
]
  template = " {{ .HEAD }}{{if .BranchStatus }} {{ .BranchStatus }}{{ end }}{{ if .Working.Changed }}  {{ .Working.String }}{{ end }}{{ if and (.Working.Changed) (.Staging.Changed) }} |{{ end }}{{ if .Staging.Changed }}  {{ .Staging.String }}{{ end }}{{ if gt .StashCount 0 }}  {{ .StashCount }}{{ end }} "

    [blocks.segments.properties]
    branch_icon = " "
    branch_identical_icon = "●"
    branch_max_length = 25
    fetch_stash_count = true
    fetch_status = true

  [[blocks.segments]]
  type = "battery"
  style = "powerline"
  foreground = "black"
  background = "white"
  background_templates = [
  "{{if eq \"Charging\" .State.String}}cyan{{end}}",
  "{{if eq \"Discharging\" .State.String}}lightYellow{{end}}",
  "{{if eq \"Full\" .State.String}}green{{end}}",
  "{{if eq \"Not Charging\" .State.String}}blue{{end}}"
]
  template = " {{ if not .Error }}{{ .Icon }} {{ .Percentage }}{{ end }}% "

    [blocks.segments.properties]
    not_charging_icon = " "
    discharging_icon = "󰚦 "
    charging_icon = "󰚥 "
    charged_icon = " "

[[blocks]]
type = "prompt"
alignment = "left"
newline = true

  [[blocks.segments]]
  type = "status"
  style = "plain"
  foreground = "lightMagenta"
  foreground_templates = [ "{{ if gt .Code 0 }}white{{ end }}" ]
  template = ""

    [blocks.segments.properties]
    always_enabled = true

[transient_prompt]
foreground = "lightWhite"
background = "transparent"
template = " {{ .PWD }}  "

