"$schema" = 'https://starship.rs/config-schema.json'

format = '''$directory$git_branch$git_status$git_state$direnv$java$ruby$nix_shell
$character'''

right_format = "$memory_usage$battery"

[time]
disabled = false

[git_status]
format = "([$all_status$ahead_behind]($style) )"
# format ="([\\$all_status$ahead_behind]($style))"
style = "green"
stashed = "󰴮 "
modified = "󰏫 "
staged = "󰶍 "
untracked = "󰊇"

[ruby]
symbol = " "
format = "[$symbol($version )]($style)"

[git_branch]
style = "green"
symbol = " "

[character]
error_symbol = "[❯](inverted)"

[battery]
format = "[$symbol $percentage]($style) "
full_symbol = "󱊣"
charging_symbol = "󰚥"
unknown_symbol = "󱈑"

[[battery.display]]
threshold = 100
style = "green"
discharging_symbol = "󱊣"

[[battery.display]]
threshold = 75
style = "green"

[[battery.display]]
threshold = 50
style = "yellow"
discharging_symbol = "󱊢"

[[battery.display]]
threshold = 20
style = "yellow"
discharging_symbol = "󱊡"

[[battery.display]]
threshold = 0
style = "red"
discharging_symbol = "󰂃"

[nix_shell]
disabled = false
format = "[$symbol$state( \\($name\\))]($style) "
symbol = "󰜗 "
