"$schema" = 'https://starship.rs/config-schema.json'

format = '''$directory$git_branch$git_status$git_state$direnv$java$ruby$node$custom
$character'''

right_format = "$memory_usage$battery"

[time]
disabled = false

[directory]
style = "bold cyan"

[git_status]
format = "([$all_status$ahead_behind]($style) )"
style = "yellow"
stashed = "󰴮 "
modified = "󰏫 ($count) "
staged = "󰶍 "
untracked = "󰊇 ($count) "

[ruby]
symbol = " "
format = "[$symbol($version )]($style)"

[git_branch]
style = "yellow"
symbol = " "

[character]
success_symbol = "[❯](bold cyan)"
error_symbol = "[❯](inverted)"

[battery]
format = "[$symbol $percentage]($style) "
full_symbol = "󱊣"
charging_symbol = "󰚥"
unknown_symbol = "󱈑"

[[battery.display]]
threshold = 100
style = "green"
discharging_symbol = "󱊣"

[[battery.display]]
threshold = 75
style = "green"

[[battery.display]]
threshold = 50
style = "yellow"
discharging_symbol = "󱊢"

[[battery.display]]
threshold = 20
style = "yellow"
discharging_symbol = "󱊡"

[[battery.display]]
threshold = 0
style = "red"
discharging_symbol = "󰂃"

[nix_shell]
disabled = false
format = "[$symbol$state( \\($name\\))]($style) "
symbol = "󰜗 "

[custom.devbox]
description = "Shows the devbox version if inside a devbox directory"
detect_files = ["devbox.json"]
command = "devbox version"
style="bold blue"
symbol = ""
format = "[$symbol v($output )]($style)"

[custom.direnv]
description = "Shows the status of direnv if inside a directory with a .envrc and devbox.json"
detect_files = [".envrc"]
shell = "sh"
command = '''
if [[ -f ./devbox.json ]]; then
  direnv_output=$(direnv status)
  if echo $direnv_output | grep -q "Found RC allowed true"; then
    echo ""
  else
    echo " direnv is blocked"
  fi
fi
'''
