{ pkgs, ... }: {
  imports = [
    ../modules/home.nix
  ];
  home = with pkgs; {
    username = "tom.monaghan";
    homeDirectory = "/Users/tom.monaghan";
    packages = [
      nodejs_18
      nodePackages.pnpm
      yarn
      rubyPackages_3_2.solargraph
      ollama
    ];
  };

  xdg.configFile.hotel = {
    target = "fish/conf.d/hotel/fish";
    text = ''# DO NOT EDIT: this file was generated by hotel and will be overwritten
direnv hook fish | source
set -gx NIX_SSL_CERT_FILE '/Library/Application Support/Netskope/STAgent/data/nscacert_combined.pem'
set -gx DIRENV_WARN_TIMEOUT '1h'
'';
  };
  xdg.configFile.hotel-completions = {
    target = "fish/completions/hotel.fish";
    source = ../dots/hotel-completions.fish;
  };
  # TODO: the below option and DIRENV_WARN_TIMEOUT live together
  xdg.configFile.direnv = {
    target = "direnv/direnv.toml";
    text = ''
      [global]
      hide_env_diff = true
    '';
  };
  programs.fish.functions = {
    clone = {
      description = "Clone a cultureamp repo";
      body = ''if set -q argv[2]
                  git clone git@github.com:cultureamp/"$argv[1]" "$argv[2..-1]"
               else
                  git clone git@github.com:cultureamp/"$argv[1]"
                  cd "$argv[1]"
               end'';
    };
  };

  programs.awscli = {
    enable = true;
  };
}
