{ pkgs, ... }: {
  imports = [
    ../home.nix
  ];
  home = with pkgs; {
    username = "tom.monaghan";
    homeDirectory = "/Users/tom.monaghan";
    packages = [
      nodejs_18
      nodePackages.pnpm
      rtx
      yarn
      rubyPackages_3_2.solargraph
    ];
  };

  programs.fish.functions = {
    clone = {
      description = "Clone a cultureamp repo";
      body = ''git clone git@github.com:cultureamp/"$argv[1]"'';
    };
  };

  programs.fish.interactiveShellInit = ''
    ### Do not edit. This was autogenerated by 'bootstrap.sh' ###
    set -gx DIRENV_BIN /Users/tom.monaghan/.nix-profile/bin/direnv
    \/Users/tom.monaghan/.nix-profile/bin/direnv hook fish | source
    set -gx NIX_SSL_CERT_FILE '/Library/Application Support/Netskope/STAgent/data/nscacert_combined.pem'
  '';
}
