{ ...}:
{
  home = {
    username = "alanturing";
    homeDirectory = "/Users/alanturing";
};
    programs.zsh.initExtra = ''fpath+=(/Users/tmonaghan/.nix-profile/share/zsh/site-functions)
### Do not edit. This was autogenerated by 'bootstrap.sh' ###
export DIRENV_BIN="/Users/alanturing/.nix-profile/bin/direnv"
eval "$($DIRENV_BIN hook zsh)"'';
}

