{ pkgs, ...}:
{
  home = with pkgs; {
    username = "tmonaghan";
    homeDirectory = "/Users/tmonaghan";
    packages = [
      unstable.devbox
    ];
  };
    programs.zsh.initExtra = ''fpath+=(/Users/tmonaghan/.nix-profile/share/zsh/site-functions)
    ### Do not edit. This was autogenerated by 'bootstrap.sh' ###
    # Actually brought in after changes to work VM on nixfiles
export DIRENV_BIN="/Users/tmonaghan/.nix-profile/bin/direnv"
eval "$($DIRENV_BIN hook zsh)"'';
}
