{ ... }:
{
  home = {
    username = "alanturing";
    homeDirectory = "/Users/alanturing";
  };
  programs.fish.interactiveShellInit = ''
    ### Do not edit. This was autogenerated by 'bootstrap.sh' ###
    set -gx DIRENV_BIN /Users/alanturing/.nix-profile/bin/direnv
    \/Users/alanturing/.nix-profile/bin/direnv hook fish | source
    set -gx NIX_SSL_CERT_FILE '/Library/Application Support/Netskope/STAgent/data/nscacert_combined.pem'
  '';
}

