#!/usr/bin/env bash
if ! command -v home-manager &> /dev/null; then
  nix shell nixpkgs#home-manager --command home-manager switch --impure --flake .#"$1"
else
  home-manager switch --impure --flake .#"$1"
fi
